### ISSUE TITLE
'zoom' event should be 'zoomend'

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/Leaflet.Canvas-Markers#11]
https://github.com/IITC-CE/Leaflet.Canvas-Markers/blob/153525e045e1c4ec22a0ecb02d965366e99852a0/src/plugin/leaflet.canvas-markers.js#L43

I suppose here meant `'zoomend'`, as for 'zoom' documentation says:

> Fired repeatedly during any change in zoom level, including zoom and fly animations.

**Comment by modos189** [comment]
yes

**Comment by johnd0e** [comment]
> yes

But `zoomend` seems excessive too, as with every zoom we also get `moveend` event.
3 times!
`dragend` also come 3 times in row.

So we have a bunch of unneeded redraws now.

**Edit**
We have 3 layers, so it's normal.

**Comment by johnd0e** [comment]
I wonder if we really need to redraw on every move.

Well, here in IITC I am pretty sure that we don't.
But it may be still useful for other uses.

**Comment by johnd0e** [comment]
I was wrong.
That fix should be reverted.
We need 'zoom' at least for pinch zoom.
