### ISSUE TITLE
L.circleMarker not working

### ISSUE THREAD

**Issue by md-seb** [IITC-CE/Leaflet.Canvas-Markers#15]
I wanted to use L.circleMarker, but the plugin fails with

Uncaught TypeError: Cannot read property 'load' of undefined
at leaflet.canvas-markers.js:386

I looked at the source but I don't see any code handling SVG markers. Am I missing anything?

**Comment by johnd0e** [comment]
We use circleMarker for portals without any issue.

Please show sample code to reproduce your problem

**Comment by johnd0e** [comment]
1. Current dev branch is https://github.com/IITC-CE/Leaflet.Canvas-Markers/tree/getevents
2. L.CircleMarker is not relevant to this project at all. Only L.Marker is supported

**Comment by md-seb** [comment]
git clone git@github.com:IITC-CE/Leaflet.Canvas-Markers.git
cd Leaflet.Canvas-Markers
git checkout getevents
npm install
npm install leaflet
npm run build
cd dist
cp leaflet.canvas-markers.js /roads-seb/libs/

see http://www.metdesk.com/roads-seb/libs/index.html

**Comment by johnd0e** [comment]
~~You must either preload `rbush`, or use `leaflet.canvas-markers.standalone.js`.~~

**Comment by md-seb** [comment]
using leaflet.canvas-markers.standalone.js makes no difference, see updated http://www.metdesk.com/roads-seb/libs/index.html

**Comment by johnd0e** [comment]
Ok, I see now.
Change `_full.js` to
```js
window.rbush = require("rbush");
var factory = require("./plugin/leaflet.canvas-markers");

window.L.CanvasIconLayer = factory(L);
```
Then build and use `leaflet.canvas-markers.js`.

For sample usage see **updated** `index.html`.
