### ISSUE TITLE
Base on another fork?

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/Leaflet.Canvas-Markers#9]
Currently our repo is based on Spaction's fork of original repo, which add this single commit: https://github.com/Spaction/Leaflet.Canvas-Markers/commit/153525e045e1c4ec22a0ecb02d965366e99852a0

Unfortunately I found that we've already reverted some parts: https://github.com/IITC-CE/Leaflet.Canvas-Markers/commit/dc89a690933b4cea13c6342340fd8e3798de4112.
So I wonder, should we ever base our work on it?
Or better start from original repo?

**Comment by modos189** [comment]
However, we are based on changes Spaction's fork. Does it make sense to transfer our changes to new fork?

**Comment by johnd0e** [comment]
No, I suppose that easier leave it as is for now.
But we may need to do it in future.

**Comment by johnd0e** [comment]
> But we may need to do it in future.

I do not like current code base.
Instead of continuously support it may be easier to implement our, simplest version.
Simplest because currently in our project we need only a part of existing here features.

**Comment by modos189** [comment]
I don't mind, but it will require to move branches and issues to a new repository

**Comment by johnd0e** [comment]
> I don't mind

Well, I mean to develop our CanvasMarker plugin from scratch.
Current issues and branches just will not be applicable in new project.

And I haven't meant that we should drop current CanvasMarkerLayer right now, 'cause we do not have any replacement (and it will require some efforts to develop one).

**Comment by modos189** [comment]
Ok. Perhaps it should be done, because we have a lot of changes compared to original project

**Comment by johnd0e** [comment]
Well, not so much, comparing to the rest of code.
And in current state it's enough for our ornaments.

But when we'll need it for real markers, with events, overlays, popups - it will be necessary to fix it again, again, and again. So in that point I suppose we should to think about alternatives.

P.S.
Please answer also this comment: https://github.com/IITC-CE/Leaflet.Canvas-Markers/commit/71eab756484bf298384f5059f15d2fd86fb0b182#commitcomment-33502466
